from sqlalchemy import String, Float, Integer, DateTime, ForeignKey, func, Text, JSON
from sqlalchemy.orm import Mapped, mapped_column
from app.core.database import Base
import uuid


class UserProfile(Base):
    __tablename__ = "user_profiles"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id: Mapped[str] = mapped_column(String, unique=True, nullable=False)  # email
    zip_code: Mapped[str | None] = mapped_column(String(20))
    city: Mapped[str | None] = mapped_column(String(200))
    lat: Mapped[float | None] = mapped_column(Float)
    lng: Mapped[float | None] = mapped_column(Float)
    search_radius_km: Mapped[float] = mapped_column(Float, default=80.0)
    priority: Mapped[str] = mapped_column(String(20), default="price")  # price | speed | local
    material_interests: Mapped[list | None] = mapped_column(JSON)
    created_at: Mapped[DateTime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[DateTime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class LocalSupplier(Base):
    __tablename__ = "local_suppliers"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id: Mapped[str] = mapped_column(String, nullable=False)  # email

    # OSM provenance
    osm_id: Mapped[str | None] = mapped_column(String(50))
    osm_type: Mapped[str | None] = mapped_column(String(20))  # node | way | relation
    name: Mapped[str] = mapped_column(String(500), nullable=False)
    address: Mapped[str | None] = mapped_column(Text)
    phone: Mapped[str | None] = mapped_column(String(50))
    website: Mapped[str | None] = mapped_column(Text)
    lat: Mapped[float | None] = mapped_column(Float)
    lng: Mapped[float | None] = mapped_column(Float)
    distance_km: Mapped[float | None] = mapped_column(Float)
    osm_tags: Mapped[dict | None] = mapped_column(JSON)
    material_categories: Mapped[list | None] = mapped_column(JSON)

    # Scrape lifecycle
    # pending | scraping | scraped | failed | no_website | login_required
    scrape_status: Mapped[str] = mapped_column(String(30), default="pending")
    scrape_error: Mapped[str | None] = mapped_column(Text)
    products_found: Mapped[int] = mapped_column(Integer, default=0)
    last_scraped_at: Mapped[DateTime | None] = mapped_column(DateTime(timezone=True))

    rank_score: Mapped[float | None] = mapped_column(Float)
    discovered_at: Mapped[DateTime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class ScraperTemplate(Base):
    """Cached CSS selector or strategy config per domain, generated by any scrape strategy."""
    __tablename__ = "scraper_templates"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    domain: Mapped[str] = mapped_column(String(200), unique=True, nullable=False)
    # shopify | woocommerce | json_ld | css | ai_generated
    strategy: Mapped[str] = mapped_column(String(30), nullable=False)
    template_data: Mapped[dict | None] = mapped_column(JSON)
    success_count: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[DateTime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    last_used_at: Mapped[DateTime | None] = mapped_column(DateTime(timezone=True))
