from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, delete
from app.core.database import get_db
from app.models.product import Product
from datetime import datetime, timezone
import uuid

router = APIRouter()

DEMO_PRODUCTS = [
    # --- GRIMCO VINYL ---
    {
        "supplier_name": "grimco",
        "sku": "GR-3M-IJ180C",
        "title": "3M Scotchcal IJ180C-10 White Gloss Vinyl Film 54\"",
        "brand": "3M",
        "material_category": "Vinyl",
        "dimensions_length": None,
        "dimensions_width": 54.0,
        "dimensions_thickness": None,
        "color": "White",
        "finish": "Gloss",
        "price": 189.50,
        "normalized_price": 0.54,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.grimco.com/products/3m-ij180c",
    },
    {
        "supplier_name": "grimco",
        "sku": "GR-3M-IJ180C-BLK",
        "title": "3M Scotchcal IJ180C-10 Black Gloss Vinyl Film 54\"",
        "brand": "3M",
        "material_category": "Vinyl",
        "dimensions_length": None,
        "dimensions_width": 54.0,
        "dimensions_thickness": None,
        "color": "Black",
        "finish": "Gloss",
        "price": 189.50,
        "normalized_price": 0.54,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.grimco.com/products/3m-ij180c-black",
    },
    {
        "supplier_name": "grimco",
        "sku": "GR-ORAJET-3951",
        "title": "Orajet 3951 Cast Vinyl Film 54\" x 50yd Matte White",
        "brand": "Oracal",
        "material_category": "Vinyl",
        "dimensions_length": 50.0,
        "dimensions_width": 54.0,
        "dimensions_thickness": None,
        "color": "White",
        "finish": "Matte",
        "price": 164.00,
        "normalized_price": 0.44,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 1,
        "product_url": "https://www.grimco.com/products/orajet-3951",
    },
    {
        "supplier_name": "grimco",
        "sku": "GR-AVERY-MPI1005",
        "title": "Avery MPI 1005 EZ RS Supercast Vinyl 60\" x 25yd",
        "brand": "Avery Dennison",
        "material_category": "Vinyl",
        "dimensions_length": 25.0,
        "dimensions_width": 60.0,
        "dimensions_thickness": None,
        "color": "White",
        "finish": "Gloss",
        "price": 142.75,
        "normalized_price": 0.57,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.grimco.com/products/avery-mpi1005",
    },
    {
        "supplier_name": "grimco",
        "sku": "GR-3M-WRAP-1080",
        "title": "3M 1080 Gloss Black Vehicle Wrap Vinyl 60\" x 5yd",
        "brand": "3M",
        "material_category": "Vinyl",
        "dimensions_length": 5.0,
        "dimensions_width": 60.0,
        "dimensions_thickness": None,
        "color": "Black",
        "finish": "Gloss",
        "price": 74.99,
        "normalized_price": 1.50,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 1,
        "product_url": "https://www.grimco.com/products/3m-1080-gloss-black",
    },
    {
        "supplier_name": "grimco",
        "sku": "GR-3M-WRAP-1080-MATTE",
        "title": "3M 1080 Matte Black Vehicle Wrap Vinyl 60\" x 5yd",
        "brand": "3M",
        "material_category": "Vinyl",
        "dimensions_length": 5.0,
        "dimensions_width": 60.0,
        "dimensions_thickness": None,
        "color": "Black",
        "finish": "Matte",
        "price": 79.99,
        "normalized_price": 1.60,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": False,
        "lead_time_days": 5,
        "product_url": "https://www.grimco.com/products/3m-1080-matte-black",
    },
    # --- GRIMCO ALUMINUM ---
    {
        "supplier_name": "grimco",
        "sku": "GR-ALU-4X8-040",
        "title": "Aluminum Sign Blank 4' x 8' .040 White",
        "brand": None,
        "material_category": "Aluminum",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 0.040,
        "color": "White",
        "finish": "Painted",
        "price": 38.50,
        "normalized_price": 0.10,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 3,
        "product_url": "https://www.grimco.com/products/aluminum-blank-4x8",
    },
    {
        "supplier_name": "grimco",
        "sku": "GR-ALU-2X4-063",
        "title": "Aluminum Sign Blank 2' x 4' .063 Mill Finish",
        "brand": None,
        "material_category": "Aluminum",
        "dimensions_length": 48.0,
        "dimensions_width": 24.0,
        "dimensions_thickness": 0.063,
        "color": "Silver",
        "finish": "Mill",
        "price": 19.75,
        "normalized_price": 0.21,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 3,
        "product_url": "https://www.grimco.com/products/aluminum-blank-2x4-063",
    },
    {
        "supplier_name": "grimco",
        "sku": "GR-DIBOND-4X8",
        "title": "Dibond Aluminum Composite 4' x 8' .118 White",
        "brand": "Dibond",
        "material_category": "Aluminum",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 0.118,
        "color": "White",
        "finish": "Gloss",
        "price": 89.00,
        "normalized_price": 0.23,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.grimco.com/products/dibond-4x8",
    },
    # --- GRIMCO SUBSTRATE ---
    {
        "supplier_name": "grimco",
        "sku": "GR-SINTRA-4X8-3MM",
        "title": "Sintra PVC Foam Board 4' x 8' 3mm White",
        "brand": "Sintra",
        "material_category": "Substrate",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 3.0,
        "color": "White",
        "finish": "Matte",
        "price": 24.50,
        "normalized_price": 0.06,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 1,
        "product_url": "https://www.grimco.com/products/sintra-3mm-white",
    },
    {
        "supplier_name": "grimco",
        "sku": "GR-FOAM-4X8-12",
        "title": "Foam Board 4' x 8' 1/2\" White Double-Sided",
        "brand": None,
        "material_category": "Foam Board",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 12.7,
        "color": "White",
        "finish": "Matte",
        "price": 8.95,
        "normalized_price": 0.02,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 1,
        "product_url": "https://www.grimco.com/products/foam-board-4x8",
    },
    {
        "supplier_name": "grimco",
        "sku": "GR-CORO-4X8-4MM",
        "title": "Coroplast Corrugated Plastic 4' x 8' 4mm White",
        "brand": "Coroplast",
        "material_category": "Coroplast",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 4.0,
        "color": "White",
        "finish": "Matte",
        "price": 11.25,
        "normalized_price": 0.03,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 1,
        "product_url": "https://www.grimco.com/products/coroplast-4mm",
    },
    # --- GRIMCO LAMINATE ---
    {
        "supplier_name": "grimco",
        "sku": "GR-3M-8519-LAM",
        "title": "3M Scotchcal 8519 Gloss Overlaminate 54\" x 50yd",
        "brand": "3M",
        "material_category": "Laminate",
        "dimensions_length": 50.0,
        "dimensions_width": 54.0,
        "dimensions_thickness": None,
        "color": "Clear",
        "finish": "Gloss",
        "price": 129.00,
        "normalized_price": 0.35,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.grimco.com/products/3m-8519-laminate",
    },
    {
        "supplier_name": "grimco",
        "sku": "GR-ORALAM-352",
        "title": "Oralam 352 Matte Overlaminate 54\" x 50yd",
        "brand": "Oracal",
        "material_category": "Laminate",
        "dimensions_length": 50.0,
        "dimensions_width": 54.0,
        "dimensions_thickness": None,
        "color": "Clear",
        "finish": "Matte",
        "price": 109.50,
        "normalized_price": 0.30,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.grimco.com/products/oralam-352",
    },
    # --- GRIMCO LED ---
    {
        "supplier_name": "grimco",
        "sku": "GR-LED-MOD-SMD",
        "title": "LED Module SMD 5050 Waterproof White 12V Pack/100",
        "brand": None,
        "material_category": "LED",
        "dimensions_length": None,
        "dimensions_width": None,
        "dimensions_thickness": None,
        "color": "White",
        "finish": None,
        "price": 34.99,
        "normalized_price": 0.35,
        "normalized_unit": "unit",
        "pack_quantity": 100,
        "in_stock": True,
        "lead_time_days": 3,
        "product_url": "https://www.grimco.com/products/led-module-smd5050",
    },
    {
        "supplier_name": "grimco",
        "sku": "GR-LED-STRIP-5M",
        "title": "LED Strip Light 5M 12V 60LED/m Warm White Waterproof",
        "brand": None,
        "material_category": "LED",
        "dimensions_length": 196.85,
        "dimensions_width": None,
        "dimensions_thickness": None,
        "color": "Warm White",
        "finish": None,
        "price": 22.50,
        "normalized_price": 4.50,
        "normalized_unit": "linear ft",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.grimco.com/products/led-strip-5m",
    },
    # --- GRIMCO HARDWARE ---
    {
        "supplier_name": "grimco",
        "sku": "GR-STANDOFF-1IN",
        "title": "Standoff Sign Mount 1\" Diameter Brushed Steel Pack/4",
        "brand": None,
        "material_category": "Hardware",
        "dimensions_length": None,
        "dimensions_width": None,
        "dimensions_thickness": None,
        "color": "Silver",
        "finish": "Brushed",
        "price": 12.99,
        "normalized_price": 3.25,
        "normalized_unit": "unit",
        "pack_quantity": 4,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.grimco.com/products/standoff-1in",
    },
    {
        "supplier_name": "grimco",
        "sku": "GR-CHANNELCAP-RED",
        "title": "Channel Letter Face Cap Return Trim Red 1\" x 50ft",
        "brand": None,
        "material_category": "Hardware",
        "dimensions_length": 600.0,
        "dimensions_width": None,
        "dimensions_thickness": None,
        "color": "Red",
        "finish": None,
        "price": 45.00,
        "normalized_price": 0.90,
        "normalized_unit": "linear ft",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 3,
        "product_url": "https://www.grimco.com/products/channel-cap-red",
    },
    # --- FELLERS VINYL ---
    {
        "supplier_name": "fellers",
        "sku": "FE-AVERY-SW900",
        "title": "Avery SW900 Supreme Wrapping Film Gloss White 60\" x 5yd",
        "brand": "Avery Dennison",
        "material_category": "Vinyl",
        "dimensions_length": 5.0,
        "dimensions_width": 60.0,
        "dimensions_thickness": None,
        "color": "White",
        "finish": "Gloss",
        "price": 65.00,
        "normalized_price": 1.30,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.ffrps.com/store/avery-sw900-white",
    },
    {
        "supplier_name": "fellers",
        "sku": "FE-AVERY-SW900-BLK",
        "title": "Avery SW900 Supreme Wrapping Film Gloss Black 60\" x 5yd",
        "brand": "Avery Dennison",
        "material_category": "Vinyl",
        "dimensions_length": 5.0,
        "dimensions_width": 60.0,
        "dimensions_thickness": None,
        "color": "Black",
        "finish": "Gloss",
        "price": 65.00,
        "normalized_price": 1.30,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.ffrps.com/store/avery-sw900-black",
    },
    {
        "supplier_name": "fellers",
        "sku": "FE-ORACLE-651",
        "title": "Oracal 651 Intermediate Cal Vinyl 24\" x 10yd Gloss White",
        "brand": "Oracal",
        "material_category": "Vinyl",
        "dimensions_length": 10.0,
        "dimensions_width": 24.0,
        "dimensions_thickness": None,
        "color": "White",
        "finish": "Gloss",
        "price": 28.50,
        "normalized_price": 0.95,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 1,
        "product_url": "https://www.ffrps.com/store/oracal-651-white",
    },
    {
        "supplier_name": "fellers",
        "sku": "FE-ORACLE-631",
        "title": "Oracal 631 Removable Vinyl 24\" x 10yd Matte White",
        "brand": "Oracal",
        "material_category": "Vinyl",
        "dimensions_length": 10.0,
        "dimensions_width": 24.0,
        "dimensions_thickness": None,
        "color": "White",
        "finish": "Matte",
        "price": 26.75,
        "normalized_price": 0.89,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 1,
        "product_url": "https://www.ffrps.com/store/oracal-631-white",
    },
    {
        "supplier_name": "fellers",
        "sku": "FE-ORACLE-751C",
        "title": "Oracal 751C Cast Vinyl 54\" x 50yd High Performance White",
        "brand": "Oracal",
        "material_category": "Vinyl",
        "dimensions_length": 50.0,
        "dimensions_width": 54.0,
        "dimensions_thickness": None,
        "color": "White",
        "finish": "Gloss",
        "price": 174.00,
        "normalized_price": 0.47,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.ffrps.com/store/oracal-751c",
    },
    {
        "supplier_name": "fellers",
        "sku": "FE-3M-1080-CF",
        "title": "3M 1080 Carbon Fiber Black Vehicle Wrap 60\" x 5yd",
        "brand": "3M",
        "material_category": "Vinyl",
        "dimensions_length": 5.0,
        "dimensions_width": 60.0,
        "dimensions_thickness": None,
        "color": "Black",
        "finish": "Carbon Fiber",
        "price": 89.99,
        "normalized_price": 1.80,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": False,
        "lead_time_days": 7,
        "product_url": "https://www.ffrps.com/store/3m-1080-carbon-fiber",
    },
    # --- FELLERS LAMINATE ---
    {
        "supplier_name": "fellers",
        "sku": "FE-AVERY-DOL1460",
        "title": "Avery DOL 1460Z Gloss Clear Laminate 54\" x 50yd",
        "brand": "Avery Dennison",
        "material_category": "Laminate",
        "dimensions_length": 50.0,
        "dimensions_width": 54.0,
        "dimensions_thickness": None,
        "color": "Clear",
        "finish": "Gloss",
        "price": 118.00,
        "normalized_price": 0.32,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.ffrps.com/store/avery-dol1460",
    },
    {
        "supplier_name": "fellers",
        "sku": "FE-AVERY-DOL1460M",
        "title": "Avery DOL 1460Z Matte Clear Laminate 54\" x 50yd",
        "brand": "Avery Dennison",
        "material_category": "Laminate",
        "dimensions_length": 50.0,
        "dimensions_width": 54.0,
        "dimensions_thickness": None,
        "color": "Clear",
        "finish": "Matte",
        "price": 122.50,
        "normalized_price": 0.33,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.ffrps.com/store/avery-dol1460m",
    },
    # --- FELLERS SUBSTRATE ---
    {
        "supplier_name": "fellers",
        "sku": "FE-GATOR-4X8-3",
        "title": "Gatorboard Foam Board 4' x 8' 3/16\" White",
        "brand": "Gatorboard",
        "material_category": "Foam Board",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 4.76,
        "color": "White",
        "finish": "Matte",
        "price": 18.50,
        "normalized_price": 0.05,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.ffrps.com/store/gatorboard-4x8",
    },
    {
        "supplier_name": "fellers",
        "sku": "FE-CORO-4X8-4MM-YEL",
        "title": "Coroplast Corrugated Plastic 4' x 8' 4mm Yellow",
        "brand": "Coroplast",
        "material_category": "Coroplast",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 4.0,
        "color": "Yellow",
        "finish": "Matte",
        "price": 12.00,
        "normalized_price": 0.031,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 1,
        "product_url": "https://www.ffrps.com/store/coroplast-yellow",
    },
    # --- FELLERS INK ---
    {
        "supplier_name": "fellers",
        "sku": "FE-EPSON-HDK-1L",
        "title": "Epson HDK Ink 1L Magenta UltraChrome",
        "brand": "Epson",
        "material_category": "Ink",
        "dimensions_length": None,
        "dimensions_width": None,
        "dimensions_thickness": None,
        "color": "Magenta",
        "finish": None,
        "price": 89.00,
        "normalized_price": 89.00,
        "normalized_unit": "unit",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 3,
        "product_url": "https://www.ffrps.com/store/epson-hdk-magenta",
    },
    {
        "supplier_name": "fellers",
        "sku": "FE-ROLAND-ECO-CYN",
        "title": "Roland Eco-Sol MAX Ink 220ml Cyan",
        "brand": "Roland",
        "material_category": "Ink",
        "dimensions_length": None,
        "dimensions_width": None,
        "dimensions_thickness": None,
        "color": "Cyan",
        "finish": None,
        "price": 42.00,
        "normalized_price": 42.00,
        "normalized_unit": "unit",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.ffrps.com/store/roland-ecosol-cyan",
    },
    # --- GLANTZ VINYL ---
    {
        "supplier_name": "glantz",
        "sku": "GL-3M-IJ35C",
        "title": "3M Controltac IJ35C Premium Vinyl 54\" x 50yd White",
        "brand": "3M",
        "material_category": "Vinyl",
        "dimensions_length": 50.0,
        "dimensions_width": 54.0,
        "dimensions_thickness": None,
        "color": "White",
        "finish": "Gloss",
        "price": 215.00,
        "normalized_price": 0.58,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.gfrps.com/store/3m-ij35c",
    },
    {
        "supplier_name": "glantz",
        "sku": "GL-ORACLE-970RA",
        "title": "Oracal 970RA Premium Wrapping Cast Film 60\" x 5yd Gloss Black",
        "brand": "Oracal",
        "material_category": "Vinyl",
        "dimensions_length": 5.0,
        "dimensions_width": 60.0,
        "dimensions_thickness": None,
        "color": "Black",
        "finish": "Gloss",
        "price": 72.50,
        "normalized_price": 1.45,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.gfrps.com/store/oracal-970ra-black",
    },
    {
        "supplier_name": "glantz",
        "sku": "GL-ORACLE-970RA-RED",
        "title": "Oracal 970RA Premium Wrapping Cast Film 60\" x 5yd Gloss Red",
        "brand": "Oracal",
        "material_category": "Vinyl",
        "dimensions_length": 5.0,
        "dimensions_width": 60.0,
        "dimensions_thickness": None,
        "color": "Red",
        "finish": "Gloss",
        "price": 72.50,
        "normalized_price": 1.45,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.gfrps.com/store/oracal-970ra-red",
    },
    {
        "supplier_name": "glantz",
        "sku": "GL-ORACLE-951-GOLD",
        "title": "Oracal 951 Premium Cast Vinyl 24\" x 10yd Gloss Gold",
        "brand": "Oracal",
        "material_category": "Vinyl",
        "dimensions_length": 10.0,
        "dimensions_width": 24.0,
        "dimensions_thickness": None,
        "color": "Gold",
        "finish": "Gloss",
        "price": 38.00,
        "normalized_price": 1.27,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 1,
        "product_url": "https://www.gfrps.com/store/oracal-951-gold",
    },
    # --- GLANTZ ALUMINUM ---
    {
        "supplier_name": "glantz",
        "sku": "GL-ALU-4X8-040-WHT",
        "title": "Aluminum Sign Blank 4' x 8' .040 Painted White Smooth",
        "brand": None,
        "material_category": "Aluminum",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 0.040,
        "color": "White",
        "finish": "Painted",
        "price": 36.00,
        "normalized_price": 0.094,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.gfrps.com/store/aluminum-4x8-040",
    },
    {
        "supplier_name": "glantz",
        "sku": "GL-ALUPANEL-4X8",
        "title": "Alupanel Aluminum Composite Panel 4' x 8' .118 White",
        "brand": "Alupanel",
        "material_category": "Aluminum",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 0.118,
        "color": "White",
        "finish": "Painted",
        "price": 82.00,
        "normalized_price": 0.21,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 3,
        "product_url": "https://www.gfrps.com/store/alupanel-4x8",
    },
    # --- GLANTZ SUBSTRATE ---
    {
        "supplier_name": "glantz",
        "sku": "GL-SINTRA-4X8-6MM",
        "title": "Sintra PVC Foam Board 4' x 8' 6mm White",
        "brand": "Sintra",
        "material_category": "Substrate",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 6.0,
        "color": "White",
        "finish": "Matte",
        "price": 32.00,
        "normalized_price": 0.083,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 1,
        "product_url": "https://www.gfrps.com/store/sintra-6mm",
    },
    {
        "supplier_name": "glantz",
        "sku": "GL-CORO-4X8-4MM",
        "title": "Coroplast Corrugated Plastic 4' x 8' 4mm White",
        "brand": "Coroplast",
        "material_category": "Coroplast",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 4.0,
        "color": "White",
        "finish": "Matte",
        "price": 10.50,
        "normalized_price": 0.027,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 1,
        "product_url": "https://www.gfrps.com/store/coroplast-4mm-white",
    },
    # --- GLANTZ ACRYLIC ---
    {
        "supplier_name": "glantz",
        "sku": "GL-ACRYLIC-4X8-18",
        "title": "Clear Acrylic Sheet 4' x 8' 1/8\" Cast",
        "brand": None,
        "material_category": "Acrylic",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 3.175,
        "color": "Clear",
        "finish": "Gloss",
        "price": 64.00,
        "normalized_price": 0.167,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 3,
        "product_url": "https://www.gfrps.com/store/acrylic-clear-4x8",
    },
    {
        "supplier_name": "glantz",
        "sku": "GL-ACRYLIC-4X8-14",
        "title": "White Acrylic Sheet 4' x 8' 1/4\" Cast",
        "brand": None,
        "material_category": "Acrylic",
        "dimensions_length": 96.0,
        "dimensions_width": 48.0,
        "dimensions_thickness": 6.35,
        "color": "White",
        "finish": "Matte",
        "price": 98.00,
        "normalized_price": 0.255,
        "normalized_unit": "ft²",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 3,
        "product_url": "https://www.gfrps.com/store/acrylic-white-4x8",
    },
    # --- GLANTZ LED ---
    {
        "supplier_name": "glantz",
        "sku": "GL-LED-NEON-FLEX",
        "title": "LED Neon Flex 24V White 16.4ft Roll IP65",
        "brand": None,
        "material_category": "LED",
        "dimensions_length": 196.85,
        "dimensions_width": None,
        "dimensions_thickness": None,
        "color": "White",
        "finish": None,
        "price": 48.00,
        "normalized_price": 2.90,
        "normalized_unit": "linear ft",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 4,
        "product_url": "https://www.gfrps.com/store/led-neon-flex-white",
    },
    {
        "supplier_name": "glantz",
        "sku": "GL-LED-DRIVER-60W",
        "title": "LED Power Supply Driver 60W 12V Waterproof",
        "brand": None,
        "material_category": "LED",
        "dimensions_length": None,
        "dimensions_width": None,
        "dimensions_thickness": None,
        "color": None,
        "finish": None,
        "price": 18.50,
        "normalized_price": 18.50,
        "normalized_unit": "unit",
        "pack_quantity": 1,
        "in_stock": True,
        "lead_time_days": 3,
        "product_url": "https://www.gfrps.com/store/led-driver-60w",
    },
    # --- GLANTZ HARDWARE ---
    {
        "supplier_name": "glantz",
        "sku": "GL-STANDOFF-SS-34",
        "title": "Stainless Steel Standoff 3/4\" Diameter 1/2\" Barrel Pack/10",
        "brand": None,
        "material_category": "Hardware",
        "dimensions_length": None,
        "dimensions_width": None,
        "dimensions_thickness": None,
        "color": "Silver",
        "finish": "Polished",
        "price": 24.99,
        "normalized_price": 2.50,
        "normalized_unit": "unit",
        "pack_quantity": 10,
        "in_stock": True,
        "lead_time_days": 2,
        "product_url": "https://www.gfrps.com/store/standoff-ss-34",
    },
]


@router.post("/seed")
async def seed_products(db: AsyncSession = Depends(get_db)):
    """Populate the database with demo products for development/demo purposes."""
    # Clear existing products
    await db.execute(delete(Product))

    # Insert demo products
    products = []
    for data in DEMO_PRODUCTS:
        product = Product(
            id=str(uuid.uuid4()),
            last_scraped_at=datetime.now(timezone.utc),
            **data,
        )
        products.append(product)
        db.add(product)

    await db.commit()
    return {"seeded": len(products), "message": f"Inserted {len(products)} demo products"}


@router.delete("/seed")
async def clear_products(db: AsyncSession = Depends(get_db)):
    """Clear all products from the database."""
    await db.execute(delete(Product))
    await db.commit()
    return {"message": "All products cleared"}


@router.delete("/purge-non-tier1")
async def purge_non_tier1(db: AsyncSession = Depends(get_db)):
    """Delete every product not from Blue Ridge, McLogan, or USCutter."""
    from sqlalchemy import not_
    TIER1 = ("blue_ridge", "mclogan", "uscutter")
    result = await db.execute(
        delete(Product).where(Product.supplier_name.not_in(TIER1))
    )
    await db.commit()
    return {"deleted": result.rowcount, "message": f"Removed {result.rowcount} non-tier-1 products"}
