"""add image_url and description to products

Revision ID: 343454d93d3a
Revises: cce1bb511848
Create Date: 2026-03-15 23:31:31.673192

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '343454d93d3a'
down_revision: Union[str, None] = 'cce1bb511848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
