"""initial schema

Revision ID: 7fe5ed8a4e28
Revises: 
Create Date: 2026-03-11 14:58:52.450002

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7fe5ed8a4e28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('material_category', sa.String(), nullable=True),
    sa.Column('dimensions_length', sa.Float(), nullable=True),
    sa.Column('dimensions_width', sa.Float(), nullable=True),
    sa.Column('dimensions_thickness', sa.Float(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('finish', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('normalized_price', sa.Float(), nullable=True),
    sa.Column('normalized_unit', sa.String(), nullable=True),
    sa.Column('pack_quantity', sa.Integer(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('session_data', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volume_pricing',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volume_pricing')
    op.drop_table('supplier_connections')
    op.drop_table('price_history')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
